import sqlite3
#print("hello")
conn =sqlite3.connect("Youtube_videos.db")
cur=conn.cursor()
#print("hiii babes")
cur.execute("CREATE TABLE IF NOT EXISTS youtube_videos(id INTEGER,tittle text , url text)")
#print("hello baby")
cur.execute("INSERT INTO youtube_videos VALUES(12,'Video_12','https://www.youtube.com/watch?v=Ae7yiE6Sx38')")
#cur.execute("INSERT INTO youtube_videos VALUES(2,'Video_2','https:////www.youtube.com//watch?v=0Zp0dvT3nCQ')")
#cur.execute("INSERT INTO youtube_videos VALUES(3,'Video_3','https://www.youtube.com/watch?v=sayK41hPXyM')")
#cur.execute("INSERT INTO youtube_videos VALUES(4,'Video_4','https://www.youtube.com/watch?v=KyOPKQZUaJA')")
cur.execute("SELECT *FROM youtube_videos")
conn.commit()
db=cur.fetchall()
print(db)
conn.commit()
conn.close()
