import sqlite3
#print("hello")
conn =sqlite3.connect("Youtube_sub_mail.db")
cur=conn.cursor()
#print("hiii babes")
cur.execute("CREATE TABLE IF NOT EXISTS youtube_subscibers(id INTEGER,name text,gmail text,phone text)")
#print("hello baby")
#cur.execute("INSERT INTO youtube_subscibers VALUES(192,'nootan kumar 1234','k.nootankumar@gmail.com','8341417422')")
#cur.execute("INSERT INTO youtube_subscibers VALUES(246,'nootan kumar 12345','kasipuri.nootan.16cse@bml.edu.in','8295041781')")
#cur.execute("INSERT INTO youtube_subscibers VALUES(182,'Ayyappa','bala.ayyappa.16cse@bml.edu.in','9490741688')")
cur.execute("INSERT INTO youtube_subscibers VALUES(217,'golla','golla.srinivas.16cse@bml.edu.in','7989806467')")
#cur.execute("INSERT INTO youtube_subscibers VALUES(192,'Bosu','bosu.sai.16cse@bml.edu.in','8295059589')")
#cur.execute("DELETE from youtube_subscibers where gamil != ?", ('k.nootankumar@gmail.com',))
cur.execute("SELECT gmail FROM youtube_subscibers")
conn.commit()
db=cur.fetchall()
print(db)
conn.commit()
conn.close()
